const popupRoot = document.createElement("div");
popupRoot.classList.add("custom_page_background_bing_popup");
const popupTitle = document.createElement("div");
const titleIcon = document.createElement("img");
titleIcon.src = chrome.runtime.getURL("icons/icon48.png");
popupTitle.appendChild(titleIcon);
const titleText = document.createElement("h1");
titleText.innerText = "カスタム背景からのお知らせ";
popupTitle.appendChild(titleText);
popupRoot.appendChild(popupTitle);
const popupBody1 = document.createElement("p");
popupBody1.innerText = "こちらのbingのトップページも背景挿入の対象のページとなっています。挿入された背景を表示するには、画面右上の「設定とクリックリンク」から、「ホームページの画像を表示」をオフにして下さい。";
popupRoot.appendChild(popupBody1);
const popupBody2 = document.createElement("p");
popupBody2.innerText = "今すぐbingのホームページの画像を非表示にしますか？";
popupRoot.appendChild(popupBody2);
const buttons = document.createElement("div");
const yesButton = document.createElement("button");
yesButton.classList.add("highlight");
yesButton.innerText = "はい";
buttons.appendChild(yesButton);
const noButton = document.createElement("button");
noButton.innerText = "いいえ";
buttons.append(noButton);
popupRoot.appendChild(buttons);
document.body.appendChild(popupRoot);